# taps
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"

# brew install
brew "libyaml"
brew "openssl@1.1"
brew "readline", link: true
brew "ansible"
brew "asciinema"
brew "aspell"
brew "binutils"
brew "libffi"
brew "cmake"
brew "libmpc"
brew "gcc"
brew "chezmoi"
brew "cookiecutter"
brew "coreutils", link: true
brew "llvm"
brew "gawk"
brew "make", link: false
brew "ctags"
brew "curl"
brew "editorconfig"
brew "exa"
brew "fd"
brew "gnupg"
brew "gnuplot"
brew "go", link: true, force: true
brew "htop"
brew "httpie"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "zlib"
brew "git"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "wget"
brew "d12frosted/emacs-plus/emacs-plus@28", args: ["with-no-frame-refocus", "with-native-comp"], link: true
brew "sqlite3"
brew "git-delta"

cask "alacritty"
cask "docker"
cask "font-jetbrains-mono"
cask "font-powerline-symbols"
cask "insomnia"
cask "spotify"
cask "telegram"
cask "firefox"
cask "whatsapp"
cask "slack"
cask "discord"
